laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::get('/home', 'ProductController@index')->middleware('auth');


Route::resource('cart','CartController');
Route::resource('product-categories','ProductCategoryController')->middleware('auth');
Route::resource('products','ProductController')->middleware('auth');
Route::resource('orders','OrderController')->middleware('auth');
Route::resource('customers','CustomerController')->middleware('auth');

Route::post('/ajax/upload-image/{image_id}','App\AjaxController@uploadImage')->middleware('auth');
Route::post('/ajax/upload-category-image/{image_id}','App\AjaxController@uploadCategoryImage')->middleware('auth');
Route::post('/ajax/delete-logo','App\AjaxController@deleteImage')->middleware('auth');
Route::post('/ajax/add-to-card','App\AjaxController@addToCard');
Route::post('/ajax/delete-from-cart','App\AjaxController@deleteFromCart');
Route::post('/ajax/update-cart','App\AjaxController@updateCart');
Route::post('/ajax/cart-table','App\AjaxController@cartTable');
Route::delete('/ajax/delete-product','App\AjaxController@deleteProduct');

//Route::get('/about', 'TestController@showAbout');
Route::get('/contact', 'TestController@showContact');

Route::view('/about', 'welcome');

laravel/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Product extends Model implements HasMedia
{

    use HasMediaTrait;

    protected $primaryKey = 'product_id';

    public function getStatusColorAttribute() {
        switch ($this->status) {
            case 'enabled':
                return 'green';
            case 'disabled':
                return "red";
            case 'out_of_stock':
                return "orange";
        }
    }


    public function getImageUrlAttribute() {
        $media = $this->getFirstMedia('image');
        if($media) return $media->getUrl('thumb');
        else return env('APP_URL').'/assets/images/no.png';
    }

    public function getThumbxsUrlAttribute() {
        $media = $this->getFirstMedia('image');
        if($media) return $media->getUrl('thumbxs');
        else return env('APP_URL').'/assets/images/logo.png';
    }

    public function getImageUrlFormAttribute() {
        $media = $this->getFirstMedia('image');
        if($media) return $media->getUrl('thumb');
        else return '';
    }

    public function registerMediaCollections()
    {
        $this->addMediaCollection('image')
            ->singleFile();
    }

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')
            ->height(300)->width(300)
            ->nonQueued();
        $this->addMediaConversion('thumbxs')
            ->height(32)->width(32)
            ->nonQueued();


    }

}

laravel/resources/views/categories/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="page-header">
            <h1 class="page-title">
                Edit Product Category
            </h1>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-3 mb-4">
                @include('components.leftpane')
            </div>
            <div class="col-md-9">
                <div class="card">
                    <div class="card-status bg-indigo"></div>
                    {{ Form::open(['route' => ['product-categories.store'], 'method' => 'POST']) }}
                    {{--<div class="card-header">
                        <h3 class="card-title">{{ __('Edit Profile') }}</h3>
                    </div>--}}
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ Form::label('title',__('Title'),['class' => 'form-label']) }}
                                    @php $err = $errors->has('title') ? ' is-invalid' : '' @endphp
                                    {{ Form::text('title',null,['class' => 'form-control'.$err , 'placeholder' => '']) }}
                                    <small>{{ $errors->first('title') }}</small>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ Form::label('short_desc',__('Short Description'),['class' => 'form-label']) }}
                                    {{ Form::text('short_desc',null,['class' => 'form-control '.($errors->has('short_desc') ? ' is-invalid' : ''), 'style' => '']) }}
                                    <small>{{ $errors->first('short_desc') }}</small>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 col-md-12">
                                <div class="form-group">
                                    {{ Form::label('long_desc',__('Long Description'),['class' => 'form-label']) }}
                                    <div class="input-group">
                                        {{ Form::textarea('long_desc',null,['class' => 'form-control '.($errors->has('long_desc') ? ' is-invalid' : ''), 'style' => '']) }}
                                        <error field="long_desc"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <button type="submit" class="btn btn-primary">{{ __('Submit') }}</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
    </div>
    </div>
@endsection

@section('footer')
@endsection

laravel/resources/views/categories/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="page-header">
            <h1 class="page-title">
                Edit Product Category
            </h1>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-3 mb-4">
                @include('components.leftpane')
            </div>
            <div class="col-md-9">
                <div class="card">
                    <div class="card-status bg-indigo"></div>
                    {{ Form::model($category, ['route' => ['product-categories.update', $category], 'method' => 'PUT']) }}
                    {{--<div class="card-header">
                        <h3 class="card-title">{{ __('Edit Profile') }}</h3>
                    </div>--}}
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ Form::label('title',__('Title'),['class' => 'form-label']) }}
                                    @php $err = $errors->has('title') ? ' is-invalid' : '' @endphp
                                    {{ Form::text('title',null,['class' => 'form-control'.$err , 'placeholder' => '']) }}
                                    <span>{{ $errors->first('title') }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ Form::label('short_desc',__('Short Description'),['class' => 'form-label']) }}
                                    <div class="input-group">
                                        {{ Form::text('short_desc',null,['class' => 'form-control '.($errors->has('short_desc') ? ' is-invalid' : ''), 'style' => '']) }}
                                        <error field="short_desc"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 col-md-12">
                                <div class="form-group">
                                    {{ Form::label('long_desc',__('Long Description'),['class' => 'form-label']) }}
                                    <div class="input-group">
                                        {{ Form::textarea('long_desc',null,['class' => 'form-control '.($errors->has('long_desc') ? ' is-invalid' : ''), 'style' => '']) }}
                                        <error field="long_desc"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <button type="submit" class="btn btn-primary">{{ __('Submit') }}</button>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Image</h3>
                        @if($category->getFirstMedia('image'))
                            <div class="card-options">
                                <a href="#" class="btn btn-secondary btn-sm delete-logo">{{ __('Delete Image') }}</a>
                            </div>
                        @endif
                    </div>
                    <div class="card-body">
                        <img id="comp-logo" src="{{ asset($category->image_url) }}" alt="logo" class="mb-5">
                        <input type="file"
                               class="filepond"
                               name="filepond"
                               multiple
                               data-max-file-size="3MB"
                               data-max-files="3"/>
                    </div>
                </div>
            </div>
        </div>

    </div>
    </div>
    </div>
@endsection

@section('footer')
    <script>
        const inputElement = document.querySelector('input[type="file"]');
        FilePond.registerPlugin(
            FilePondPluginImagePreview
        );
        FilePond.setOptions({
            server: {
                url: '/ajax/upload-category-image/{{ $category->category_id }}',
                process: {
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                }
            },
            labelIdle: 'Umiestnite súbory alebo <span class="filepond--label-action">Prehľadávajte</span>',
        });
        const pond = FilePond.create(inputElement);
        pond.onprocessfile = (error, file) => {
            if (error) {
                console.log('Oh no');
                return;
            }
            location.reload();
        }

    </script>
@endsection

laravel/resources/views/categories/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="page-header">
            <h1 class="page-title">
                Categories
            </h1>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-3 col-md-2 mb-2">
                @include('components.leftpane')
            </div>
            <div class="col-lg-9 col-md-2">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Category List</h3>
                        <div class="card-options">
                            <a href="{{ route('product-categories.create') }}" class="btn btn-primary btn-sm">Add Category</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="card-status bg-indigo"></div>
                        <table class="table table-hover table-outline table-vcenter text-nowrap card-table"
                               style="overflow: auto">
                            <thead>
                            <tr>
                                <th></th>
                                <th>Title</th>
                                <th class="text-center">Created At</th>
                                <th class="text-center">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($categories as $category)
                                <tr>
                                    <td>
                                    <span class="avatar" style="background-image: url({{ $category->thumbxs_url }})">
                                        <span class="avatar-status bg-orange"></span>
                                    </span>
                                    </td>
                                    <td>{{ $category->title }}</td>
                                    <td style="text-align: center">{{ $category->created_at }}</td>
                                    <td class="text-center">
                                        <a
                                                href="{{ route('product-categories.edit',['category' => $category->category_id]) }}"
                                                class="btn btn-secondary btn-sm">Edit</a>
                                        {{ Form::open(['route' => ['product-categories.destroy',$category->category_id], 'method' => 'delete', 'style'=> 'display:inline-block' ] ) }}
                                        <button class="btn btn-secondary btn-sm">Delete</button>
                                        {{ Form::close() }}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection