laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::get('/home', 'ProductController@index')->middleware('auth');


Route::resource('cart','CartController');
Route::resource('product-categories','ProductCategoryController')->middleware('auth');
Route::resource('products','ProductController')->middleware('auth');
Route::resource('orders','OrderController')->middleware('auth');
Route::resource('customers','CustomerController')->middleware('auth');

Route::post('/ajax/upload-image/{image_id}','App\AjaxController@uploadImage')->middleware('auth');
Route::post('/ajax/upload-category-image/{image_id}','App\AjaxController@uploadCategoryImage')->middleware('auth');
Route::post('/ajax/delete-logo','App\AjaxController@deleteImage')->middleware('auth');
Route::post('/ajax/add-to-card','App\AjaxController@addToCard');
Route::post('/ajax/delete-from-cart','App\AjaxController@deleteFromCart');
Route::post('/ajax/update-cart','App\AjaxController@updateCart');
Route::post('/ajax/cart-table','App\AjaxController@cartTable');
Route::delete('/ajax/delete-product','App\AjaxController@deleteProduct');

//Route::get('/about', 'TestController@showAbout');
Route::get('/contact', 'TestController@showContact');

Route::view('/about', 'welcome');

laravel/app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cart = \Cart::content();
        return view('cart.index',['cart' => $cart]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

laravel/resources/views/cart/index.blade.php
@extends('layouts.www')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Shopping Cart</h3>
                    <div class="card-options">
                        <a href="{{ route('products.create') }}" class="btn btn-primary btn-sm">Add Product</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="card-status bg-indigo"></div>
                    <table class="table table-hover table-outline table-vcenter text-nowrap card-table"
                           style="overflow: auto">
                        <thead>
                        <tr>
                            <th></th>
                            <th>Title</th>
                            <th class="text-center">Qty</th>
                            <th class="text-right">Price</th>
                            <th class="text-right">Subtotal</th>
                            <th class="text-center">Actions</th>
                        </tr>
                        </thead>
                        <tbody id="cart-body">
                        @foreach($cart as $item)
                            <tr>
                                <td>
                                    <span class="avatar" style="background-image: url({{ $item->options->thumb }})">
                                        <span class="avatar-status bg-orange"></span>
                                    </span>
                                </td>
                                <td>{{ $item->name }}</td>
                                <td class="text-center">
                                    @if($item->qty > 1)
                                        <button class="btn btn-secondary btn-sm btn-update-cart"
                                                data-id="{{ $item->rowId }}" data-qty="{{ ($item->qty - 1) }}"
                                                style="margin-right: 5px">-</button>
                                    @else
                                        <button class="btn btn-secondary btn-sm disabled" style="margin-right: 5px">-
                                        </button>
                                    @endif{{ $item->qty }}
                                    <button class="btn btn-secondary btn-sm btn-update-cart" data-id="{{ $item->rowId }}"
                                            data-qty="{{ ($item->qty + 1) }}" style="margin-left: 5px">+</button>
                                </td>
                                <td class="text-right">${{ $item->price }}</td>
                                <td class="text-right">${{ $item->subtotal }}</td>
                                <td class="text-center">
                                    {{-- <a
                                             href="{{ route('products.edit',['product' => $product->product_id]) }}"
                                             class="btn btn-secondary btn-sm">Spravuj</a>--}}
                                    <button class="btn btn-secondary btn-sm btn-cart-delete"
                                            data-id="{{ $item->rowId }}">Delete
                                    </button>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
@endsection